// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASe9g9KfPYN_P_9DfRtNwGjYCWY3e_zCs',
    appId: '1:472336418917:web:1810e4e327700153a95e8c',
    messagingSenderId: '472336418917',
    projectId: 'dinein-18fe0',
    authDomain: 'dinein-18fe0.firebaseapp.com',
    storageBucket: 'dinein-18fe0.appspot.com',
    measurementId: 'G-PE37PZF35K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX7HEG4k_MhIffdh1wSRVTXcyMTE1SKGk',
    appId: '1:472336418917:android:3c4bc77d2acea397a95e8c',
    messagingSenderId: '472336418917',
    projectId: 'dinein-18fe0',
    storageBucket: 'dinein-18fe0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADunwkmF_2QAgDRV_JYrBYrku2UeIY38M',
    appId: '1:472336418917:ios:219f147c6ba6588aa95e8c',
    messagingSenderId: '472336418917',
    projectId: 'dinein-18fe0',
    storageBucket: 'dinein-18fe0.appspot.com',
    iosBundleId: 'com.example.dineIn',
  );
}
