// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTWcMk1iOd12iyyp9h1ly9hELlN_uX5bM',
    appId: '1:218149286986:web:5444108d4ae6e9c04862b3',
    messagingSenderId: '218149286986',
    projectId: 'dinein-d3df1',
    authDomain: 'dinein-d3df1.firebaseapp.com',
    storageBucket: 'dinein-d3df1.appspot.com',
    measurementId: 'G-N5F2CFY7T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXC6zEIMhK5f1BzWuC6HMUoRz1QdXi3Vk',
    appId: '1:218149286986:android:5ae2f44281ccbd834862b3',
    messagingSenderId: '218149286986',
    projectId: 'dinein-d3df1',
    storageBucket: 'dinein-d3df1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlbseIdh8zcWn9qyTHsP1Gaw_NlR37jEU',
    appId: '1:218149286986:ios:3734e6a17df3c34a4862b3',
    messagingSenderId: '218149286986',
    projectId: 'dinein-d3df1',
    storageBucket: 'dinein-d3df1.appspot.com',
    iosBundleId: 'com.dinIn.dineInResturant',
  );
}
